routes/admin.php
<?php
/*
 * All routes for admin portal
 *
 * Item Name: Ultimate SMS - Bulk SMS Application For Marketing
 * Author: Codeglen
 * Author URL: https://codecanyon.net/user/codeglen
 */

Route::get('/dashboard', 'AdminBaseController@index')->name('home');

/*
|--------------------------------------------------------------------------
| Customer module
|--------------------------------------------------------------------------
|
| Route for Customer module
|
*/

Route::post('customers/search', 'CustomerController@search')->name('customers.search');
Route::get('customers/export', 'CustomerController@export')->name('customers.export');
Route::get('customers/{customer}/show', 'CustomerController@show')->name('customers.show');
Route::get('customers/{customer}/impersonate', 'CustomerController@impersonate')->name('customers.login_as');
Route::get('customers/{customer}/assign-plan', 'CustomerController@show')->name('customers.assign_plan');
Route::get('customers/{customer}/avatar', 'CustomerController@avatar')->name('customers.avatar');
Route::post('customers/{customer}/avatar', 'CustomerController@updateAvatar');
Route::post('customers/{customer}/remove-avatar', 'CustomerController@removeAvatar');
Route::post('customers/{customer}/add-unit', 'CustomerController@addUnit')->name('customers.add_unit');
Route::post('customers/{customer}/remove-unit', 'CustomerController@removeUnit')->name('customers.remove_unit');
Route::post('customers/{customer}/update-information', 'CustomerController@updateInformation')->name('customers.update_information');
Route::post('customers/{customer}/permissions', 'CustomerController@permissions')->name('customers.permissions');
Route::post('customers/{customer}/active', 'CustomerController@activeToggle')->name('customers.active');
Route::post('customers/batch_action', 'CustomerController@batchAction')->name('customers.batch_action');

Route::resource('customers', 'CustomerController', [
        'only' => ['index', 'create', 'store', 'update', 'destroy'],
]);

/*
|--------------------------------------------------------------------------
| Subscription module
|--------------------------------------------------------------------------
|
| Route for Subscription module
|
*/

Route::post('subscriptions/search', 'SubscriptionController@search')->name('subscriptions.search');
Route::post('subscriptions/{subscription}/approve-pending', 'SubscriptionController@approvePending')->name('subscriptions.approve_pending');
Route::post('subscriptions/{subscription}/reject-pending', 'SubscriptionController@rejectPending')->name('subscriptions.reject_pending');
Route::post('subscriptions/{subscription}/renew', 'SubscriptionController@renew')->name('subscriptions.renew');
Route::post('subscriptions/{subscription}/cancel', 'SubscriptionController@cancel')->name('subscriptions.cancel');
Route::get('subscriptions/{subscription}/logs', 'SubscriptionController@logs')->name('subscriptions.logs');
Route::get('subscriptions/{subscription}/change-plan', 'SubscriptionController@changePlan')->name('subscriptions.change_plan');
Route::post('subscriptions/{subscription}/change-plan', 'SubscriptionController@changePlan');
Route::post('subscriptions/batch_action', 'SubscriptionController@batchAction')->name('subscriptions.batch_action');

Route::resource('subscriptions', 'SubscriptionController', [
        'only' => ['index', 'create', 'store', 'destroy'],
]);

/*
|--------------------------------------------------------------------------
| Currency module
|--------------------------------------------------------------------------
|
| Route for Currency module
|
*/

Route::post('currencies/search', 'CurrencyController@search')->name('currencies.search');
Route::get('currencies/export', 'CurrencyController@export')->name('currencies.export');
Route::get('currencies/{currency}/show', 'CurrencyController@show')->name('currencies.show');
Route::post('currencies/{currency}/active', 'CurrencyController@activeToggle')->name('currencies.active');
Route::post('currencies/batch_action', 'CurrencyController@batchAction')->name('currencies.batch_action');

Route::resource('currencies', 'CurrencyController', [
        'only' => ['index', 'create', 'store', 'update', 'destroy'],
]);

/*
|--------------------------------------------------------------------------
| Sending servers module
|--------------------------------------------------------------------------
|
| Route for Sending servers module
|
*/

Route::post('sending-servers/search', 'SendingServerController@search')->name('sending-servers.search');
Route::get('sending-servers/select', 'SendingServerController@select')->name('sending-servers.select');
Route::get('sending-servers/create/{type}', 'SendingServerController@create')->name('sending-servers.create');
Route::get('sending-servers/export', 'SendingServerController@export')->name('sending-servers.export');
Route::get('sending-servers/{server}/show', 'SendingServerController@show')->name('sending-servers.show');
Route::post('sending-servers/{server}/active', 'SendingServerController@activeToggle')->name('sending-servers.active');
Route::post('sending-servers/custom-server/create', 'SendingServerController@addCustomServer')->name('sending-servers.add.custom');
Route::post('sending-servers/custom-server/update/{sending_server}', 'SendingServerController@updateCustomServer')->name('sending-servers.update.custom');
Route::post('sending-servers/batch_action', 'SendingServerController@batchAction')->name('sending-servers.batch_action');

Route::resource('sending-servers', 'SendingServerController', [
        'only' => ['index', 'store', 'update', 'destroy'],
]);


//Plan For Plan module
/**
 * Plan details
 * 1. Name of plan
 * 2. Price for plan
 * 3. description (optional)
 * 4. Billing cycle (Daily, Monthly, yearly, custom - [integer amount with day, week, month, year]
 * 5. Currency
 * 6. Billing Information (optional)
 *
 * Quota
 * 1. SMS Sending Credits
 * 2. Max List/Phone book
 * 3. Max Subscriber
 * 4. Max subscriber per list
 *
 * Plan features
 * 1. Customer can import list
 * 2. Customer can export list
 * 3. Customer can use API
 * 4. Customer can create own sending server
 * 5. Customer can create sub-accounts
 * 6. Customer can delete sms history
 * 7. Add Previous sms balance on next subscription
 * 8. Sender ID Verification
 *
 * Pricing
 * 1. Coverage country
 * 2. plain, voice, mms, whatsapp message price
 *
 *Speed Limit
 * 1. Set a limit [unlimited, 100 sms per minute, 10000 sms per hour, 10000 sms per hour, 10,000 sms per day, 50,000 sms per day, custom - Sending Credits - Time Value - Time unit]
 * 2. Max Number of processes [1,2,3]
 *
 * Sending Servers
 * 1. Add multiple sending server (Rotate sending server when message will send)
 * 2. Set probability
 *
 */

Route::post('plans/search', 'PlanController@search')->name('plans.search');
Route::get('plans/export', 'PlanController@export')->name('plans.export');
Route::get('plans/{plan}/show', 'PlanController@show')->name('plans.show');
Route::post('plans/{plan}/active', 'PlanController@activeToggle')->name('plans.active');
Route::post('plans/{plan}/settings', 'PlanController@settingFeatures')->name('plans.settings.features');
Route::post('plans/{plan}/sending-servers', 'PlanController@addSendingServers')->name('plans.settings.sending-servers');
Route::post('plans/{plan}/update-fitness', 'PlanController@updateFitness')->name('plans.settings.update-fitness');
Route::post('plans/{plan}/set-primary', 'PlanController@setPrimary')->name('plans.settings.set-primary');
Route::post('plans/{plan}/speed-limit', 'PlanController@updateSpeedLimit')->name('plans.settings.speed-limit');
Route::post('plans/{plan}/cutting-system', 'PlanController@updateCuttingSystem')->name('plans.settings.cutting-system');
Route::post('plans/{plan}/pricing', 'PlanController@updatePricing')->name('plans.settings.pricing');
Route::get('plans/{plan}/coverage', 'PlanController@addCoverage')->name('plans.settings.coverage');
Route::post('plans/{plan}/coverage', 'PlanController@addCoveragePost');
Route::post('plans/{plan}/search', 'PlanController@searchCoverage')->name('plans.settings.search_coverage');
Route::get('plans/{plan}/edit-coverage/{coverage}', 'PlanController@editCoverage')->name('plans.settings.edit_coverage');
Route::post('plans/{plan}/edit-coverage/{coverage}', 'PlanController@editCoveragePost');
Route::post('plans/{plan}/coverage/{coverage}/active', 'PlanController@activeCoverageToggle')->name('plans.coverage.active');
Route::post('plans/{plan}/coverage/{coverage}/delete', 'PlanController@deleteCoverage')->name('plans.coverage.delete');

Route::post('plans/{plan}/delete-sending-server', 'PlanController@deletePlanSendingServer')->name('plans.settings.delete-sending-server');
Route::post('plans/{plan}/copy', 'PlanController@copy')->name('plans.copy');
Route::post('plans/batch_action', 'PlanController@batchAction')->name('plans.batch_action');

Route::resource('plans', 'PlanController', [
        'only' => ['index', 'create', 'store', 'update', 'destroy'],
]);


/*
|--------------------------------------------------------------------------
| Keywords module
|--------------------------------------------------------------------------
|
| Route for Keywords module
|
*/

Route::post('keywords/search', 'KeywordController@search')->name('keywords.search');
Route::get('keywords/export', 'KeywordController@export')->name('keywords.export');
Route::get('keywords/{keyword}/show', 'KeywordController@show')->name('keywords.show');
Route::post('keywords/{keyword}/remove-mms', 'KeywordController@removeMMS')->name('keywords.remove-mms');
Route::post('keywords/batch_action', 'KeywordController@batchAction')->name('keywords.batch_action');

Route::resource('keywords', 'KeywordController', [
        'only' => ['index', 'create', 'store', 'update', 'destroy'],
]);


/*
|--------------------------------------------------------------------------
| Sender id module

routes/web.php
<?php

use App\Http\Controllers\LanguageController;
use App\Library\Tool;
use App\Models\AppConfig;
use App\Models\Campaigns;
use App\Models\EmailTemplates;
use App\Models\PaymentMethods;
use Database\Seeders\Countries;
use Illuminate\Support\Facades\Artisan;
use Symfony\Component\Console\Output\BufferedOutput;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    if (config('app.stage') == 'new') {
        return redirect('install');
    }

    if (config('app.stage') == 'Live' && config('app.version') == '2.8') {
        return redirect('update');
    }

    return redirect('login');
});

// locale Route
Route::get('lang/{locale}', [LanguageController::class, 'swap']);
Route::any('languages', [LanguageController::class, 'languages'])->name('languages');

if (config('app.stage') == 'local') {
    Route::get('run-campaign', function () {

        $campaign = Campaigns::find(5);
        if ($campaign) {
            $campaign->singleProcess();
        }
    });

    Route::get('update-file', function (BufferedOutput $outputLog) {
        $app_path = base_path().'/bootstrap/cache/';
        if (File::isDirectory($app_path)) {
            File::cleanDirectory($app_path);
        }

        Artisan::call('optimize:clear');
        Artisan::call('migrate', ['--force' => true], $outputLog);
        Tool::versionSeeder(config('app.version'));

        AppConfig::setEnv('APP_VERSION', '3.4.0');

        return redirect()->route('login')->with([
                'status'  => 'success',
                'message' => 'You have successfully updated your application.',
        ]);
    });

    Route::get('update-country', function () {
        $countries = new Countries();
        $countries->run();
    });

    Route::get('debug', function () {

        $app_config = AppConfig::where('setting', 'login_notification_email')->first();
        if ( ! $app_config) {
            AppConfig::create([
                    'setting' => 'login_notification_email',
                    'value'   => false,
            ]);
        }

        $email_template = EmailTemplates::where('slug', 'sender_id_confirmation')->first();

        if ( ! $email_template) {
            EmailTemplates::create(
                    [
                            'name'    => 'Sender ID Confirmation',
                            'slug'    => 'sender_id_confirmation',
                            'subject' => 'Sender ID Confirmation on {app_name}',
                            'content' => 'Hi,
                                      You sender id mark as: {status}. Login to your portal to show details.
                                      {sender_id_url}',
                            'status'  => true,
                    ]);
        }

        $payment_method = PaymentMethods::where('type', 'paygateglobal')->first();
        if ( ! $payment_method) {
            PaymentMethods::create(
                    [
                            'name'    => 'PaygateGlobal',
                            'type'    => 'paygateglobal',
                            'options' => json_encode([
                                    'api_key' => 'api_key',
                            ]),
                            'status'  => true,
                    ]);
        }


        return 'success';

    });

}

Route::get('/clear', function () {

    Artisan::call('optimize:clear');

    return "Cleared!";

});

app/Http/Controllers/Customer/CustomerBaseController.php
<?php

namespace App\Http\Controllers\Customer;

use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\View\View;

class CustomerBaseController extends Controller
{
    /**
     * Show admin home.
     *
     * @return Application|Factory|\Illuminate\Contracts\View\View|View
     */
    public function index()
    {
        return view('customer.dashboard');
    }

    protected function redirectResponse(Request $request, $message, $type = 'success')
    {
        if ($request->wantsJson()) {
            return response()->json([
                    'status'  => $type,
                    'message' => $message,
            ]);
        }

        return redirect()->back()->with("flash_{$type}", $message);
    }

}

resources/views/customer/SendingServer/list.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', __('locale.menu.Sending Servers'))

@section('vendor-style')
    {{-- vendor css files --}}
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/dataTables.bootstrap5.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/responsive.bootstrap5.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/buttons.bootstrap5.min.css')) }}">

@endsection

@section('content')

    <!-- Basic table -->
    <section id="datatables-basic">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <table class="table datatables-basic">
                        <thead>
                        <tr>
                            <th></th>
                            <th>{{__('locale.labels.name')}}</th>
                            <th>{{__('locale.labels.type')}}</th>
                            <th>{{__('locale.labels.actions')}}</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach ($sending_servers as $key => $server)
                            @if($server["type"] === 'http')
                                @php $color = "success" @endphp
                            @elseif($server["type"] === 'smpp')
                                @php $color = "primary" @endphp
                            @elseif($server["type"] === 'whatsapp')
                                @php $color = "info" @endphp
                            @endif

                            @if($server['custom'] == 1)
                                @php $type = 'custom' @endphp
                            @else
                                @php $type = $server->settings @endphp
                            @endif

                            <tr>
                                <td></td>
                                <td>{{ $server['name'] }}</td>
                                <td>
                                    <span class="badge bg-{{$color}}">{{ strtoupper($server['type'])}}</span>
                                </td>
                                <td>
                                    <a href="{{route('customer.sending-servers.create', ['type' => $type])}}" class="btn btn-primary btn-sm">{{__('locale.labels.choose')}}</a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
    <!--/ Basic table -->


@endsection


@section('vendor-script')
    {{-- vendor files --}}
    <script src="{{ asset(mix('vendors/js/tables/datatable/jquery.dataTables.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/dataTables.bootstrap5.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/dataTables.responsive.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/responsive.bootstrap5.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.buttons.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.html5.min.js')) }}"></script>

@endsection
@section('page-script')
    {{-- Page js files --}}
    <script>
        $(document).ready(function () {
            "use strict"

            $('.datatables-basic').DataTable({

                "processing": true,
                "columns": [
                    {"data": "id", orderable: false, searchable: false},
                    {"data": "name"},
                    {"data": "type"},
                    {"data": "action", orderable: false, searchable: false}
                ],
                columnDefs: [
                    {
                        // For Responsive
                        className: 'control',
                        orderable: false,
                        responsivePriority: 2,
                        targets: 0
                    },
                ],
                dom: '<"d-flex justify-content-between align-items-center mx-0 row"<"col-sm-12 col-md-6"l><"col-sm-12 col-md-6"f>>t<"d-flex justify-content-between mx-0 row"<"col-sm-12 col-md-6"i><"col-sm-12 col-md-6"p>>',

                language: {
                    paginate: {
                        // remove previous & next text from pagination
                        previous: '&nbsp;',
                        next: '&nbsp;'
                    },
                    sLengthMenu: "_MENU_",
                    sZeroRecords: "{{ __('locale.datatables.no_results') }}",
                    sSearch: "{{ __('locale.datatables.search') }}",
                    sProcessing: "{{ __('locale.datatables.processing') }}",
                    sInfo: "{{ __('locale.datatables.showing_entries', ['start' => '_START_', 'end' => '_END_', 'total' => '_TOTAL_']) }}"
                },
                responsive: {
                    details: {
                        display: $.fn.dataTable.Responsive.display.modal({
                            header: function (row) {
                                let data = row.data();
                                return 'Details of ' + data['name'];
                            }
                        }),
                        type: 'column',
                        renderer: function (api, rowIdx, columns) {
                            let data = $.map(columns, function (col) {
                                return col.title !== '' // ? Do not show row in modal popup if title is blank (for check box)
                                    ? '<tr data-dt-row="' +
                                    col.rowIdx +
                                    '" data-dt-column="' +
                                    col.columnIndex +
                                    '">' +
                                    '<td>' +
                                    col.title +
                                    ':' +
                                    '</td> ' +
                                    '<td>' +
                                    col.data +
                                    '</td>' +
                                    '</tr>'
                                    : '';
                            }).join('');

                            return data ? $('<table class="table"/>').append('<tbody>' + data + '</tbody>') : false;
                        }
                    }
                },
                aLengthMenu: [[10, 20, 50, 100], [10, 20, 50, 100]],

                order: [[0, "desc"]],
                displayLength: 10,
            });

        });
    </script>

@endsection